### PR TITLE
fix build due to duplicate "static" since INLINE is defined as "static inline" - fixes #89

### LINKED ISSUE #89: [RPi3] Error compiling from the source
Couldn't compile the genesis plus gx from the source :(
the log it's in the followed link:

[rps_2017-07-26_135541.log.gz](https://github.com/libretro/Genesis-Plus-GX/files/1176817/rps_2017-07-26_135541.log.gz)

### PR DESCRIPTION
**Pull request by joolswills**

### CODE REVIEW

**Comment by joolswills** [comment]
Or you may wish to change the definition of "INLINE" as an alternative fix (and update code to include static where needed).

**Comment by twinaphex** [comment]
@ekeeke Libretro-common already uses 'INLINE' as a define -

The one in Genesis Plus GX ('static inline') cannot co-exist with this one.

Can't we change usage of 'INLINE' in the codebase in Genesis Plus GX to 'static INLINE' in order to avoid this issue? I don't see how we are going to be able to do this without any modifications anyhow.

**Comment by ekeeke** [comment]
Huh? 
https://github.com/libretro/Genesis-Plus-GX/blob/master/core/macros.h#L40
Do you remember this was done some time ago upon your request? I even replaced all static  inline in the code with this macro, only because of build failure with MSVC.
Anyway, i do not see any incompatibilities with what you are saying, if INLINE is defined elsewhere, it is not defined here.
From a quick look, the problem is actually in your libretro Makefile where you are alfeady defining INLINE
https://github.com/libretro/Genesis-Plus-GX/blob/master/Makefile.libretro#L344

Not sure why you need to have it defined in an include file now when it was fine before your last commit afaik but you have to pick one.

What is sure is that I am not going to modify whole core once again when this can be fixed on your side with some limited changes in libretro files.

**Comment by ekeeke** [comment]
Also look at one of my answer in https://github.com/libretro/Genesis-Plus-GX/pull/84 for a proper solution when declaring cdStream macros in osd.h that would avoid the need of filestream_transform wrapper. Obviously it was ignored although it solves that inlining issue.

**Comment by twinaphex** [comment]
The INLINE macro in libretro-common is set in stone, that can not be changed. We cannot afford to do breakage in libretro-common at all, too many cores and too many repos depend on it.

So we have a problem here. 

It's defined in an include file because that is what libretro-common's retro_inline.h file does, which some libretro-common files (like the filestream file which the WinRT guy is depending on) use.

Regarding your frustrations with how your suggestions are getting ignored regarding the filestream shenanigans, I am trying my best here to be as diplomatic as possible to both you and that WinRT contributor. It's a tough balancing act but I hope we can all arrive at a solution we all are satisfied with.

@albertofustinoni - Are you reading this conversation? Would you mind doing it in a way that @ekeeke prefers so we can stay upstream-compatible?

**Comment by twinaphex** [comment]
The only solution I see for now is to simply move away from these statically inlined functions. @albertofustinoni - hopefully you can incorporate these changes later on in your own work, otherwise we'd run into problems here.

**Comment by twinaphex** [comment]
This commit should negate the need for this PR -

https://github.com/libretro/Genesis-Plus-GX/commit/87cab8a36506631e199b371051fdb4b57e71fd45

@joolswills Let me know if this works, and if so, we can close this one.

**Comment by albertofustinoni** [comment]
Sorry it took me a while to figure what was going on and join the discussion.

I am ok with the change @twinaphex made: Only thing that is needed is`typedef struct RFILE RFILE` on top of file_stream_transforms.h to make the thing compile.

The exact same as file_stream.h

**Comment by ekeeke** [comment]
I don't understand why you insist on using file_stream_transforms

The solution below keeps the benefit of inlining and removes the need for intermediate function layer

in osd.h

remove

`#include <streams/file_stream_transforms.h>`

and

replace

```
#ifndef cdStream
#define cdStream            RFILE
#define cdStreamOpen(fname) rfopen(fname, "rb")
#define cdStreamClose       rfclose
#define cdStreamRead        rfread
#define cdStreamSeek        rfseek
#define cdStreamTell        rftell
#define cdStreamGets        rfgets
#endif
```

by


```
#ifdef USE_FILESTREAM
#include <streams/file_stream.h>
#define cdStream       RFILE
#define cdStreamOpen(fname)      filestream_open(fname, RFILE_MODE_READ, -1)
#define cdStreamClose(stream)      filestream_close(stream)
#define cdStreamRead(buffer, size, count, stream)  filestream_read(stream, buffer, size*count)
#define cdStreamSeek(stream, offset, origin)  filestream_seek(stream, offset, origin)
#define cdStreamTell(stream)      filestream_tell(stream)
#define cdStreamGets(buffer,length,stream)     filestream_gets(stream,buffer,length)
#endif
```

Is that really complicated?

The thing is, this is the only location where file_stream_transforms was used but it is not really needed so why bother with it and cause all these issues with incompatible inlining.

> The INLINE macro in libretro-common is set in stone, that can not be changed. We cannot afford to do breakage in libretro-common at all, too many cores and too many repos depend on it.

The INLINE macro in libretro-common also uses a #ifndef so whatever definition you use in your libretro Makefile will prelude libretro-common definition without breaking anything. It does not matter if "many cores and many repos" use libretro-common INLINE definition, this will only apply to the core for which the Makefile is used, i.e this core.

**Comment by albertofustinoni** [comment]
What about the function pointers in the vorbis file callback structure?

The function signatures are different (parameters ordering), so those macros will fail.

It was my first approach to do exactly what you are recommending but it did not compile.

**Comment by ekeeke** [comment]
>What about the function pointers in the vorbis file callback structure?
Indeed.

What about declaring function wrappers in osd.h instead for these functions ?

My point is that relying on file_stream_transforms.h is not necessary

**Comment by joolswills** [comment]
builds fine now.

**Pull request closed without merging**
