### PR TITLE
Tidy up overclock code

### PR DESCRIPTION
**Pull request by bkoropoff**
Also use full available precision for overclock ratio.

cc @ekeeke

### CODE REVIEW

**Comment by ekeeke** [comment]
I think you forgot to change in s68kcpu.c as well. 

Also I would prefer not including shared.h or osd.h in m68k core so it remains separated from the gpgx core.

- have Z80_OVERCLOCK_BITS and M68K_OVERCLOCK_BITS defined in Makefile, get ride of OVERCLOCK_SHIFT and remove macro definitions from osd.h (let HAVE_OVERCLOCK being defined in libretro.c as before since its only used here)

then, in in libretro.c:

- check for assertions regarding m68k and z80 shift values separately (although I wouldn't bother to test this if I were you since the values in Makefile are not arbitrarely chosen and shouldn't be platform specific anyway). Ideally, those shift values should be defined in cpu cores as they are core specific, but I guess that's something I can change myself later eventually.

- have config.overclock set to 100, 125, etc instead of calculated fixed point ratio then calculate m68k.cycle_ratio and  z80.cycle_ratio using config.overclock and their respective shift macro. Also you don't need to recalculate these every frames, you could simply have overclock_delay set to OVERCLOCK_DELAY + 1 on reset when config.overclock != 100 and 0 otherwise then only recalculate ratio when overclock_delay = 1. You also need to reset m68k and z80 ratios to default init values on retro_reset otherwise the delay is useless (cpu init functions are not called by gen_reset). Obviously, you will also need to force overclock_delay in check_variables to some value > 1 if overclock_delay = 0 when config.overclock value is changed, so that new ratio can still be recalculated.

**Comment by bkoropoff** [comment]
Whoops, I'll fix `s68kcpu.c`.

`shared.h` is included in `z80.c`, so I assumed it was OK.  I'll refactor to allow different shifts for each core.

**Comment by bkoropoff** [comment]
PR updated

**Comment by ekeeke** [comment]
Looks good to me. Thank you.

**Comment by bkoropoff** [comment]
@twinaphex this one's ready to go

**Comment by ekeeke** [comment]
I merged this directly into my repository, you can close this (without merging) and rather sync back with my repository instead to get this merged into libretro but also get all the latest changes to YM2612/YM3438 FM cores.

**Pull request merged**
