### PR TITLE
File access via filestream in libretro builds

### PR DESCRIPTION
**Pull request by albertofustinoni**

### CODE REVIEW

**Comment by albertofustinoni** [comment]
Got it.

I moved the defines into osd.h
Do you think it's OK now?

**Comment by ekeeke** [comment]
Yes, that's the idea.

As for having libretro-common code duplicated in core repository (and linked within the core), wouldn't it be cleaner and more optimized to extend libretro API with those function call (or maybe libretro_* wrappers that redirect to retroarch file_streams definitions) since all this code is already within retroarch?

**Comment by twinaphex** [comment]
We don't want to add file I/O to the libretro API. That is far higher level and best suited for intermediary code like libretro-common, which can get baked into the core itself. This is a hard line in the sand we draw and we aren't likely to deviate from imt.

**Comment by albertofustinoni** [comment]
@twinaphex Is there anything you'd like me to change in the pull request or are you OK with the modifications made?

`file_stream_transforms.h` is the exact same as the one in the `libretro_common` repo.

**Comment by twinaphex** [comment]
While I am generally fine with your changes, I'd like @ekeeke to be fine with them as well. I generally would like to avoid hard forks if possible, but hopefully we can reach some kind of middle ground here that will satisfy both sides here.

**Comment by albertofustinoni** [comment]
I though @eekeke was happy with the changes now that the defines are in osd.h

Did I misunderstand?

While I agree with him that file IO would be better if included in the libretro API, it is your call and you said you don't want to.

**Comment by twinaphex** [comment]
Alright, if he is OK with it, we can merge this then. I will wait for about a day, and if I hear no objection then, I will merge it.

**Comment by ekeeke** [comment]
At least, you could avoid that unneeded extra function call layer (file_stream_transforms.h) by defining the macros to directly use filestream_ API, and define them only for libretro platforms that REALLY require file virtualization or "sandboxing" like UWP (for all other platforms, this will just add another unneeded function call layer that again should be avoided when possible for optimizing file access, even if it seems negligible overhead 
).

Like this, for example (with -DUSE_FILESTREAM added in libretro makefile for platforms that really need it)

`
#ifdef USE_FILESTREAM
#define cdStream                                                 RFILE
#define cdStreamOpen(fname)                              filestream_open(fname, RFILE_MODE_READ, -1)
#define cdStreamClose(stream)                             filestream_close(stream)
#define cdStreamRead(buffer, size, count, stream)  filestream_read(stream, buffer, size*count)
#define cdStreamSeek(stream, offset, origin)          filestream_seek(stream, offset, origin)
#define cdStreamTell(stream)                                filestream_tell(stream)
#define cdStreamGets(buffer,length,stream)           filestream_gets(stream,buffer,length)
#endif
`

Apart from this (which is mainly a suggestion, I don't really care about how ports are handled), the following changes would be required to get merged in "official" core repository:

1) if you absolutely need to build the core with libretro-common, at least move that directory within /libretro directory since this will only be used by libretro port

2) the remaining modifications left in cdd.c, cdd.h and ssp16.c that force the use of libretro file_stream.h should be reverted since they are not needed anymore (note that for ssp16.c, it was not even needed considering debug file code is compiled only if USE_DEBUGGER is defined)

@twinaphex: the following commits should also be reverted since they were likely done to 'fix' compilation issue with ios after  file_stream.h was included in cdd.c and ssp16.c. 

https://github.com/libretro/Genesis-Plus-GX/commit/a410090b8ea3c78c453fb69b921a8df66d063125
https://github.com/libretro/Genesis-Plus-GX/commit/ca06614c7405e13971bbc0f23bb4d5ea665d5748
https://github.com/libretro/Genesis-Plus-GX/commit/24acab9e513d505f5b2d7bfef78fb7a27420a113
https://github.com/libretro/Genesis-Plus-GX/commit/609a13375fff588d502049f993b86fc563818621

Again this should not be needed anymore . It could eventually be done in another pull request (like this one https://github.com/libretro/Genesis-Plus-GX/pull/85 ).

Next time, if you really want to avoid "hard forks" diverging from official repository, please contact me before accepting pull requests that modify core files or doing bulk changes to core files in order to fix compilation issues witha specific platform, so that we can find a solution that please everybody. In this specific case, forcing the core to use libretro-common filestream wrapper was a very bad idea since it broke all non-libretro ports build and this should only be optional in case platform or port really need it. Similarly, all these types redefining in m68k files could have been avoided by simply moving the #include for  file_stream.h BEFORE the line #include "shared.h" in cdd.c and ssp16.c.

**Comment by twinaphex** [comment]
Regarding the m68k files, I think the world has moved past hoky stdint-alike typedefs by now and we should all be using stdint.h in this day and age. That on top of the fact that this archaic stuff was causing issues led to me just calling it a day and getting rid of it. If you want it like that, sure, I will play ball for the mere sake of you preferring it that way, even though to me it seems to be just there for legacy reasons, since the original author of m68k apparently did it that way.

Regardless, I will revert the commits you mentioned so that we are both on the same page again.

**Comment by twinaphex** [comment]
Reverted the commits and related files.

**Comment by ekeeke** [comment]
@twinaphex: yes, I prefer keeping the original files as much unchanged as possible,especially when it's not necessary or only cosmetic changes. So far, that code did not cause any problem with any platforms (the problem you had was because #include were not ordered properly in some other C files that indirectly includes m68k.h). Also note that stdint.h is C99 standard and I remember we had to do massive changes in the core to replace C99 style comments and other stuff because it would not build with microsoft compilers that did not support C99 standard.

**Comment by twinaphex** [comment]
Yeah, but for C89-style compilers like the older MSVC versions, I have an stdint.h header in libretro-common which can be used there and should be more or less adequate. So that doesn't preclude not having to use stdint.h types.

**Comment by ekeeke** [comment]
Anyway, if I simulate a pull request , there are still m68kcpu.h and m68kops.h diverging from my repository. I would prefer having only files with necessary modifications in that pull request and keep the history of those two files untouched.

Thanks

> Have you provided @albertofustinoni with enough information now as to what additional steps he needs to take before this can be merged now?

The two remaining points are quite well highlighted in my earlier comment so I guess yes

**Comment by twinaphex** [comment]
The files have been reverted to your latest. So with this, @albertofustinoni should be able to build on top of this now and do it in a way that you can agree with.

**Comment by twinaphex** [comment]
I think we're all set up here now @albertofustinoni . You might have to rebase this PR or start from scratch and then we can finally get this stuff merged now that both parties seem to be more or less satisfied with the way things are going.

**Comment by albertofustinoni** [comment]
Closing this since I started again from scratch and opened #88

**Pull request closed without merging**
