### PR TITLE
Add support for short GG cheats.

### PR DESCRIPTION
**Pull request by ilag11111**
While researching how to decode Master System Game Genie cheats for my work on Picodrive, I discovered that the last three characters are actually optional.  This change allows for cheats missing those last three characters to function without being edited.

123-456[-789]

### CODE REVIEW

**Comment by twinaphex** [comment]
Thanks for all the great work!

**Comment by Sinistrahd** [comment]
Hello ilag111111, I am trying to figure out getting the genesis PAR codes to function in Genesis_Plus_GX and have been having issues with non-functionality, I have tried, to take a single example, Sorceror's Kingdom, in several different version from the 3.00 Goodmerge. I have not been able to get a code to work on that game in either the retroarch clover implementation on nes classic or PC Retroarch updated to the latest version and core. I was wondering if you had any tips to get the codes working, as I know they do work for some users. Also, I found this on the forums ( https://forums.libretro.com/t/genesis-game-genie-cheats/5789 ) and was wondering if anything there looks promising to you. Just a disclaimer, I have virtually no coding background beyond assembler, and I ended up getting a degree other than EE because of the programming requirements :-P

**Comment by ilag11111** [comment]
For support questions regarding cheats it's best to post in my thread on the forums [here](https://forums.libretro.com/t/wip-adding-cheat-support-to-more-cores/6604).  Github is best left for development dicussion, especially on a commit relating to Game Gear cheats rather than Genesis cheats.

That being said, I'll be investigating your problem very shortly and will respond with a proper answer there.

**Comment by twinaphex** [comment]
@ilag11111 Sorry about that, I recommended him to post a message here since I wasn't aware of your presence on the forum.

**Comment by ilag11111** [comment]
No problem.  I just gave him a response now. https://forums.libretro.com/t/wip-adding-cheat-support-to-more-cores/6604/54

**Pull request merged**
