### PR TITLE
Add ios-arm64 build target; Added a new IS_IOS_OR_MAC_OS compiler fla…

### PR DESCRIPTION
**Pull request by yoshisuga**
…g; Fixed uint typedef declaration for Mac OS and iOS using this new compiler flag.

### CODE REVIEW

**Comment by yoshisuga** [comment]
I just read @ekeeke 's comment on a different pull request, saying that retroarch specific flags shouldn't be in the core, so i'll try to come up with a different more agnostic fix.

**Comment by ekeeke** [comment]
Yes, Genesis Plus is normally meant to be portable so, if there is a problem compiling it for a specific platform, I would rather have people contacting me to find a suitable solution rather than 'fixing' the core themselves with platform specific hacks or more radical solutions like replacing every 'uint' occurrence in the core because it seems the easiest/quickest solution to get that specific platform building.
In that specific case, adding an "#undef uint" before defining it in m68k.h should work if it defined elsewhere in platform specific library used to compile.


Envoyé depuis mon smartphone Samsung Galaxy.
null

**Comment by yoshisuga** [comment]
@ekeeke Can you take a look at my latest change in this PR? I just added a check for the `__APPLE_` compiler flag - the `#undef uint` doesn't work.

If you have another suggestion, let me know - thanks!

**Comment by ekeeke** [comment]
What error message do you get with original code  (i.e with #undef uint before #undef sint, which for some reason was removed in libretro forked repository) ?

original code: https://github.com/ekeeke/Genesis-Plus-GX/blob/master/core/m68k/m68k.h

**Comment by yoshisuga** [comment]
Hi, this is the error message:

```
In file included from core/cd_hw/cdd.c:39:
In file included from ./libretro-common/include/streams/file_stream.h:29:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.3.sdk/usr/include/sys/types.h:92:23: error: cannot combine with previous 'int' declaration specifier
typedef unsigned int            uint;           /* Sys V compatibility */
                                ^
./core/m68k/m68k.h:79:25: note: expanded from macro 'uint'
#define uint   unsigned int
```

**Comment by ekeeke** [comment]
What happens if you remove following lines:
https://github.com/libretro/Genesis-Plus-GX/blob/master/core/cd_hw/cdd.c#L39
and
https://github.com/libretro/Genesis-Plus-GX/blob/master/core/cd_hw/cdd.c#L133
up to
https://github.com/libretro/Genesis-Plus-GX/blob/master/core/cd_hw/cdd.c#L156

which are useless in that file (and should be removed anyway)

**Comment by yoshisuga** [comment]
Hi, I removed those lines you mentioned, but it won't compile unless I added that '#ifdef __APPLE__` to the `uint` typedef declaration.

Is it ok to add that compiler flag check?

**Comment by twinaphex** [comment]
Hi there @yoshisuga , you might want to rebase this PR since I had to revert a few commits at @ekeeke's request.

**Comment by ekeeke** [comment]
No.

Again, what is the error message ? It is more important to try to understand where the error comes from.

In this case, looking at the diff between libretro and my repository, I think you will need to remove similar lines in ssp16.c

**Comment by yoshisuga** [comment]
It wasn't my intention to alter the core's code in any way and i don't want to introduce any 'hacks-just-to-get-it-to-compile' changes.

I just wanted to fix the RetroArch-specific makefile to support the iOS arm64 architecture. I shouldn't have been meddling with the core's code without any insight to it so I apologize for that. I'll create a new pull request again based on the latest master code as it'd be easier.

That said, the compile error is the same as above:
```
In file included from core/cd_hw/cdd.c:39:
In file included from ./libretro-common/include/streams/file_stream.h:29:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.3.sdk/usr/include/sys/types.h:92:23: error: cannot combine with previous 'int' declaration specifier
typedef unsigned int            uint;           /* Sys V compatibility */
                                ^
./core/m68k/m68k.h:79:25: note: expanded from macro 'uint'
#define uint   unsigned int
```

I believe this has to do with iOS's flavor of Unix being based in its BSD roots, as `uint` is already defined in the system header.

**Comment by ekeeke** [comment]
Look at the error message

>In file included from core/cd_hw/cdd.c:39:
>In file included from ./libretro-common/include/streams/file_stream.h:29:

Are you sure you removed that line
`#include "streams/file_stream.h"`
from cdd.c like I told you above as it does not look like so?

Same line should also be removed from ssp16.c
https://github.com/libretro/Genesis-Plus-GX/blob/master/core/cart_hw/svp/ssp16.c#L193

**Comment by twinaphex** [comment]
I'll remove these lines for now so we can move forward.

**Comment by ekeeke** [comment]
This is not enough, you should also remove:

 - https://github.com/libretro/Genesis-Plus-GX/blob/795a843719ef99379831eefe6c93dec460ef1c25/core/cd_hw/cdd.c#L132 to https://github.com/libretro/Genesis-Plus-GX/blob/795a843719ef99379831eefe6c93dec460ef1c25/core/cd_hw/cdd.c#L155

- https://github.com/libretro/Genesis-Plus-GX/blob/master/core/cd_hw/cdd.h#L64

otherwise you will likely have compilation issue

and revert the changes between https://github.com/libretro/Genesis-Plus-GX/blob/795a843719ef99379831eefe6c93dec460ef1c25/core/cart_hw/svp/ssp16.c#L1018 and https://github.com/libretro/Genesis-Plus-GX/blob/795a843719ef99379831eefe6c93dec460ef1c25/core/cart_hw/svp/ssp16.c#L1024

Really, just copy back all those files (cdd.c, cdd.h, ssp16.c, m68kops.h and m68kcpu.h) from https://github.com/ekeeke/Genesis-Plus-GX/tree/master/core and the job is done.

**Comment by twinaphex** [comment]
Done. Hopefully both @yoshisuga and the guy from the other thread can now continue.

**Pull request closed without merging**
