### PR TITLE
Remove binaries.

### PR DESCRIPTION
**Pull request by orbea**
I don't know who added these, but lets not do that...

### CODE REVIEW

**Comment by orbea** [comment]
@ekeeke Actually should I have sent this to your repo?

**Comment by twinaphex** [comment]
@orbea I don't think it's a problem, especially not if @ekeeke himself prefers to do it that way. We should honor and respect the choices he makes for his own repository, after all, the software would not be available to all of us otherwise.

**Comment by orbea** [comment]
@ekeeke If you prefer it this way I will honor your wishes, but it inflates the git history a lot and its not very nice to have to download years worth of old core binaries every time the repo is cloned. Can they be hosted somewhere else?

**Comment by hizzlekizzle** [comment]
github does have the 'releases' section where you can host binary builds without it being a part of the source tree, but whatever eke wants to do is fine.

**Comment by ekeeke** [comment]
@orbea: I see, I did not thought about git history. Are these objects really copied in git local history everytime they are updated? I can see my local .git directory is ~200MB which does not seem a lot considering the amount of commits and files modified since the creation of repository. Build objects are ~10 MB so I would have imagined the .git history to have inflated much more than that.

@hizzlekizzle : problem with github releases is that I itave a look at the restrictions it has. Another solution could be to leave builds only on Genesis Plus GX bitbucket repository since that's were link is pointing to on github front page.

**Pull request closed without merging**
