### PR TITLE
Build fix

### PR DESCRIPTION
**Pull request by albertofustinoni**

### CODE REVIEW

**Comment by albertofustinoni** [comment]
@twinaphex don't know about others but without this the project doesn't build for me

**Comment by twinaphex** [comment]
Is it still necessary to merge this or not? Let me know based on the current trunk.

**Comment by albertofustinoni** [comment]
Yes please, without that forward declaration the project doesn't build.

**Comment by albertofustinoni** [comment]
Once again, thank you very much.

Are you on IRC now by chance? I'd like to ask you a couple of questions.

**Pull request merged**
