### PR TITLE
Add experimental "overclock" option

### PR DESCRIPTION
**Pull request by bkoropoff**
Like with Nestopia, this works by running the CPU for extra cycles
during the vblank period rather than actually changing the clock
speed.  It appears to alleviate slowdown without obvious ill effects,
but I haven't tested it extensively.

CD hardware update logic is more complex and delicate, so making
overclocking work for it is not so simple (I tried).  The option is
presently ignored for CDs.

This was the result of a couple hours scanning through the source code
and experimenting, so it's probably stupid and/or broken in some way.

### CODE REVIEW

**Comment by bkoropoff** [comment]
@ekeeke I tried your approach and it's more reliable than the "phantom scanline/vblank" trick used by NES emulators.  I had assumed a similar hack would be necessary, but it turns out the straightforward approach works great.

I've updated the PR appropriately.

**Comment by ekeeke** [comment]
Looks much cleaner indeed and definitively something I would have no issue merging in main repository.

Two things (in z80.c):

1) instead of 

#ifdef Z80_ALLOW_OVERCLOCK
#define CYCS(A) ((A) / z80_overclock_ratio)
#else
#define CYCS(A) (A)
#endif

I would rather have something similar to m68kcpu.h i.e

#ifdef Z80_ALLOW_OVERCLOCK
#define USE_CYCLES(A) Z80.cycles += (A) / z80_overclock_ratio
#else
#define USE_CYCLES(A) Z80.cycles += (A) 
#endif

2) in BURNODD function, just keep the original code without trying to reproduce the desired behavior which is not very clear, it is unused anyway:

`USE_CYCLES((cycles / cyclesum) * cyclesum * 15);`

**Comment by twinaphex** [comment]
@bkoropoff I am OK with merging the PR if you can take ekeekes feedback and make the last few necessary changes.

**Comment by bkoropoff** [comment]
I should have time to fix it up later today.

**Comment by bkoropoff** [comment]
@twinaphex @ekeeke 

Alright, changes made.

**Comment by James-F2** [comment]
Hi

Typically the Genesis 68K overclocked from stock 7.6 MHz to 10 or 12 MHz.
At 12 various issues with games start to appear.
http://www.sega-16.com/forum/showthread.php?22854-Overclocking-amp-68010-Annotated-Compatibility-List

What are the clock options in this experimental commit?

**Comment by twinaphex** [comment]
Played around with it, seems fine in most games. I think the tempo of the music in Sonic 2 is affected though with CPU overclocking set to 2x. Might be something worth looking into.

**Comment by bkoropoff** [comment]
2x might be too much for some games which need just a little extra headroom.  I can try adding fractional settings, although for maximum performance I would need to modify the cycle tables to remove the built-in multiplication by the standard clock divider ratio.

**Comment by ekeeke** [comment]
Issues with overclocking are unavoidable, even at 1,5x or lower as they depend on how each games were programmed: some might implement a temporization using a fixed number of nop instructions that was obtained through testing on stock hardware or timeouts which duration depends on a basic loop with a down counter. I am also sure many games that were more or less badly programmed do things that only work by chance on real hardware and having some instruction occuring a few cycle later ot before than expected would cause a crash (same thing happens sometime when you make your emulator timings more accurate regarding events and instructions decoding synchronization).

That is something people should expect when they activate this option so any issue reports with this enabled should obviously be ignored.

**Comment by blackman91** [comment]
The android version of the core doesn't have this overlock option, or Am i missing something? How do you enable it?

**Comment by blackman91** [comment]
Does anyone know how to edit the JNI makefile to add this to the android genesis plus gx core?

**Pull request merged**
