### PR TITLE
Rebase to upstream

### PR DESCRIPTION
**Pull request by ds22x**
This rebases the Libretro fork to be in sync to upstream by applying commits https://github.com/ekeeke/Genesis-Plus-GX/commit/d1e7cd6bea711f97e3c080fbbf9a1e3e1975408a to https://github.com/ekeeke/Genesis-Plus-GX/commit/751d8867d46a1c1d1887bd63211845837c0530ca from Root/libretro/, and commits https://github.com/ekeeke/Genesis-Plus-GX/commit/fbc949cc4747a6c4352dbce2ebe5ea55dbb81197 to https://github.com/ekeeke/Genesis-Plus-GX/commit/32a2edb6a6fa35b6e8b2e36f872499076bad9e6f from Root/Core/ to downstream, bringing it up to date to https://github.com/ekeeke/Genesis-Plus-GX/commit/32a2edb6a6fa35b6e8b2e36f872499076bad9e6f, committed on Feb 23, 2021.

### CODE REVIEW

**Comment by ekeeke** [comment]
Hi.

While I think it's great you are finally merging all the latest changes from my Genesis Plus GX repository, I am wondering why you are not simply  pulling and merging commits from upstream repository to libretro forked repository using the normally expected method, as described in this article: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/merging-an-upstream-repository-into-your-fork
?

I understand it might be meaningless if you only care about producing builds with up-to-date sourcecode changes and do not really care about sourcecode change history but it is important to me as it retains all the upstream commits history in your fork (for anyone interested in sourcecode changes history) and avoid upstream and libretro repository appearing this much out of sync in github (as right now your repository is not really "107 commits behind" my repository anymore, contrary to what is indicated here). This also makes automatic pull requests from libretro to upstream much easier and cleaner as they wouldn't try to merge back all these changes to upstream although that's where they come from initially.

There shouldn't be much conflict between uour changes and mine but even if there were a few, they should just as easily be mergeable to retain your local changes while getting my upstream changes (and if you have really no idea what to do with the code without breaking anything, surely I can figure it for you if you ask beforehand)

As a result,  while checking what differences remained between our two repositories, I noticed the following unexpected source differences:

- changes were copypasted back with different indentation (like tabulations instead of space characters or removed space lines) in following files:
loadrom.c
mem68k.c
memz80.c
cdd.c
scd.c

- following modified files have not up-to-date copyright date:
genesis.c
genesis.h
loadrom.c
loadrom.h
mem68k.h
memz80.h
sound.c
sound.h
scd.c
scd.h
cdd.c
cdd.h (this one also incorrectly kept renamed field "volume" in cdd_t structure definition)

- following commits fixing some core files are missing:
 https://github.com/ekeeke/Genesis-Plus-GX/commit/d927c6e4cbafdee302ab6f1edd4ae9f8f68678d8 (ssp16.c, cdd.c, state.h, state.c)
https://github.com/ekeeke/Genesis-Plus-GX/commit/ec3c90e3bca764ce6290275ea27699cf86c0f29b#diff-2b6087869e5f7d45f741cfd0e3512cb8571152fb3b70c66ad575ac34e499c10b (membnk.c, membnk.h)
https://github.com/ekeeke/Genesis-Plus-GX/commit/fbc949cc4747a6c4352dbce2ebe5ea55dbb81197 (z80.c)

- following commit was incorrectly backported (duplicated code in sms_cart.c function sms_cart_context_load):
https://github.com/ekeeke/Genesis-Plus-GX/commit/aa9300d58107e497b31ba63b3517f6fe408afb44#

- HISTORY.txt shall be updated to keep core changes history

Note that pulling and merging from upstream on a local copy of your fork, using git commands or any git frontend, should have avoided such discrepancies.

**Comment by ekeeke** [comment]
Also, after this merge, the following issue reports should probably be closed in this repository  to clean the issue page a little:
https://github.com/libretro/Genesis-Plus-GX/issues/234
https://github.com/libretro/Genesis-Plus-GX/issues/217
https://github.com/libretro/Genesis-Plus-GX/issues/209
https://github.com/libretro/Genesis-Plus-GX/issues/207
https://github.com/libretro/Genesis-Plus-GX/issues/186

and also these two duplicated ones probably:
https://github.com/libretro/Genesis-Plus-GX/issues/218
https://github.com/libretro/Genesis-Plus-GX/issues/116
https://github.com/libretro/Genesis-Plus-GX/issues/25

**Comment by ds22x** [comment]
I truly apologize if this has caused any inconvenience, but my thought process when I worked on this was that, in order to make sure upstream changes would not conflict with downstream, I would have to go through the history and cherry pick every last modification manually, which is why it got combined into one giant commit.
I'll look into rebasing it following that guide, although I'll need to make absolutely sure it doesn't break build compilation (which I believe shouldn't happen, but it's better to be safe than sorry on that part).

**Comment by ekeeke** [comment]
Thanks for your time, this looks much better now as libretro repository changes compared to upstream repository are now quite easily identificable (and mergable) via github and upstream commit history is now correctly integrated in libretro repository.

There are still the spacing/tab indentification differences in the 5 files I listed above + an incorrect copyright date in sms_cart.c but they are likely due to your first merge/copypaste commit changes which were seen as later modifications by git merger and kept as is. It should be easy to resolve these differences by a few commits in libretro repository, so that these files are as much identical as possible to upstream files (i.e with only changes being related to libretro added functionalities).

**Comment by ds22x** [comment]
That should address everything.
And thanks again for pointing out where the differences were.

**Comment by crystalct** [comment]
@ds22x is it possible to update those file form libretro-common master:
features/features_cpu.c
file/config_file.c
include/memmap.h
include/net/net_compat.h
include/retro_miscellaneous.h
include/retro_timers.h
net/net_compat.c
net/net_socket.c
rthreads/rthreads.c
streams/stdin_stream.c
vfs/vfs_implementation.c
so i could update and fix ps3/psl1ght build?

**Comment by ds22x** [comment]
I'm not quite sure what it is you're asking me, but if you want to go through those files in this repository to update and fix PS3, then be my guest.

**Comment by crystalct** [comment]
Ok, i will copy & paste from https://github.com/libretro/libretro-common what necessary to those files to make a complete PR.

**Comment by crystalct** [comment]
I've been too rushed ... none of those need to be built. :-P

**Pull request merged**
